"""Shared test fixtures for auraframes tests."""

from typing import Any

import pytest

from auraframes.client import Client


@pytest.fixture
def mock_user() -> dict[str, Any]:
    """Sample user response from login API."""
    return {
        "id": "user-123",
        "name": "Test User",
        "email": "test@example.com",
        "auth_token": "test-auth-token-abc123",
        "created_at": "2024-01-01T00:00:00Z",
        "updated_at": "2024-01-01T00:00:00Z",
        "short_id": None,
        "show_push_prompt": False,
        "latest_app_version": None,
        "attribution_id": None,
        "attribution_string": None,
        "test_account": False,
        "avatar_file_name": None,
        "has_frame": True,
        "analytics_optout": False,
        "admin_account": False,
    }


@pytest.fixture
def mock_frame() -> dict[str, Any]:
    """Sample frame response from API."""
    return {
        "id": "frame-456",
        "name": "Living Room",
        "user_id": "user-123",
        "software_version": "1.0.0",
        "build_version": "100",
        "hw_android_version": "11",
        "created_at": "2024-01-01T00:00:00Z",
        "updated_at": "2024-01-01T00:00:00Z",
        "handled_at": "2024-01-01T00:00:00Z",
        "deleted_at": None,
        "updated_at_on_client": None,
        "orientation": 1,
        "auto_brightness": True,
        "min_brightness": 10,
        "max_brightness": 100,
        "brightness": 50,
        "sense_motion": True,
        "default_speed": "normal",
        "slideshow_interval": 15,
        "slideshow_auto": True,
        "digits": 4,
        "contributors": None,
        "contributor_tokens": [],
        "hw_serial": "ABC123",
        "matting_color": "white",
        "trim_color": "black",
        "is_handling": False,
        "calibrations_last_modified_at": "2024-01-01T00:00:00Z",
        "gestures_on": True,
        "portrait_pairing_off": None,
        "live_photos_on": True,
        "auto_processed_playlist_ids": [],
        "time_zone": "America/Los_Angeles",
        "wifi_network": "HomeWifi",
        "cold_boot_at": None,
        "is_charity_water_frame": False,
        "num_assets": 100,
        "thanks_on": True,
        "frame_queue_url": None,
        "client_queue_url": "https://sqs.example.com/queue",
        "scheduled_display_sleep": False,
        "scheduled_display_on_at": None,
        "scheduled_display_off_at": None,
        "forced_wifi_state": None,
        "forced_wifi_recipient_email": None,
        "is_analog_frame": False,
        "control_type": "digital",
        "display_aspect_ratio": "16:10",
        "has_claimable_gift": None,
        "gift_billing_hint": None,
        "locale": "en",
        "frame_type": None,
        "description": None,
        "representative_asset_id": None,
        "sort_mode": None,
        "email_address": "frame@aura.com",
        "features": None,
        "letterbox_style": None,
        "user": {
            "id": "user-123",
            "name": "Test User",
            "email": "test@example.com",
            "auth_token": "token",
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-01T00:00:00Z",
            "short_id": None,
            "show_push_prompt": False,
            "latest_app_version": None,
            "attribution_id": None,
            "attribution_string": None,
            "test_account": False,
            "avatar_file_name": None,
            "has_frame": True,
            "analytics_optout": False,
            "admin_account": False,
        },
        "playlists": [],
        "delivered_frame_gift": None,
        "last_feed_item": {},
        "last_impression": None,
        "last_impression_at": "2024-01-01T00:00:00Z",
        "child_albums": [],
        "smart_adds": [],
        "recent_assets": [],
    }


@pytest.fixture
def client() -> Client:
    """Fresh HTTP client for testing."""
    return Client()


@pytest.fixture
def mock_asset() -> dict[str, Any]:
    """Sample asset response from API."""
    return {
        "auto_landscape_16_10_rect": None,
        "auto_portrait_4_5_rect": None,
        "burst_id": None,
        "burst_selection_types": None,
        "colorized_file_name": None,
        "created_at_on_client": "2024-01-01T00:00:00.000Z",
        "data_uti": "public.jpeg",
        "duplicate_of_id": None,
        "duration": None,
        "duration_unclipped": None,
        "exif_orientation": 1,
        "favorite": False,
        "file_name": "test-image.jpg",
        "glaciered_at": "2024-01-01T00:00:00.000Z",
        "good_resolution": True,
        "handled_at": "2024-01-01T00:00:00.000Z",
        "hdr": False,
        "height": 1080,
        "horizontal_accuracy": None,
        "id": "asset-789",
        "ios_media_subtypes": None,
        "is_live": False,
        "is_subscription": False,
        "landscape_16_10_url": None,
        "landscape_16_10_url_padding": None,
        "landscape_rect": None,
        "landscape_url": "https://imgproxy.pushd.com/landscape/test.jpg",
        "landscape_url_padding": None,
        "live_photo_off": None,
        "local_identifier": "local-asset-123",
        "location": [34.1978216, -77.8943033],
        "location_name": "Test Location",
        "md5_hash": "abc123md5hash",
        "minibar_landscape_url": None,
        "minibar_portrait_url": None,
        "minibar_url": None,
        "modified_at": "2024-01-01T00:00:00.000Z",
        "orientation": 1,
        "original_file_name": "original.jpg",
        "panorama": False,
        "portrait_4_5_url": None,
        "portrait_4_5_url_padding": None,
        "portrait_rect": None,
        "portrait_url": "https://imgproxy.pushd.com/portrait/test.jpg",
        "portrait_url_padding": None,
        "raw_file_name": None,
        "represents_burst": None,
        "rotation_cw": 0,
        "selected": True,
        "source_id": "source-123",
        "taken_at": "2024-01-15T12:30:45.000Z",
        "taken_at_granularity": None,
        "taken_at_user_override_at": None,
        "thumbnail_url": "https://imgproxy.pushd.com/thumb/test.jpg",
        "unglacierable": False,
        "upload_priority": 1,
        "uploaded_at": "2024-01-01T00:00:00.000Z",
        "user": {
            "id": "user-123",
            "name": "Test User",
            "email": "test@example.com",
            "auth_token": "token",
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-01T00:00:00Z",
            "short_id": None,
            "show_push_prompt": False,
            "latest_app_version": None,
            "attribution_id": None,
            "attribution_string": None,
            "test_account": False,
            "avatar_file_name": None,
            "has_frame": True,
            "analytics_optout": False,
            "admin_account": False,
        },
        "user_id": "user-123",
        "user_landscape_16_10_rect": None,
        "user_landscape_rect": None,
        "user_portrait_4_5_rect": None,
        "user_portrait_rect": None,
        "video_clip_excludes_audio": None,
        "video_clip_start": None,
        "video_clipped_by_user_at": None,
        "video_file_name": None,
        "video_url": None,
        "widget_url": None,
        "width": 1920,
    }


@pytest.fixture
def mock_activity() -> dict[str, Any]:
    """Sample activity response from API."""
    return {
        "id": "activity-123",
        "asset_count": 1,
        "comment_count": 0,
        "commenters": [],
        "created_at": "2024-01-01T00:00:00.000Z",
        "formatted_text": "Test User added 1 photo",
        "frame_id": "frame-456",
        "plain_text": "Test User added 1 photo",
        "playlist": None,
        "playlist_id": None,
        "reactions": [],
        "recent_comments": [],
        "representative_asset_ids": ["asset-789"],
        "type": "photos_added",
        "user_id": "user-123",
        "viewable_asset_count": 1,
        "suggestion_manifest": None,
        "user": {
            "id": "user-123",
            "name": "Test User",
            "email": "test@example.com",
            "auth_token": "token",
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-01T00:00:00Z",
            "short_id": None,
            "show_push_prompt": False,
            "latest_app_version": None,
            "attribution_id": None,
            "attribution_string": None,
            "test_account": False,
            "avatar_file_name": None,
            "has_frame": True,
            "analytics_optout": False,
            "admin_account": False,
        },
        "representative_assets": None,
    }
